<div class="container-fluid">
    <div>
        <h3>Payment System Settings</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Settings</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Payment System Settings</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <!--Payment System Settings (Credit system + Pro System)-->
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Payment System Settings (Credit system + Pro System)</h6>
                    <div class="payment-settings-alert"></div>
                    <form class="payment-settings" method="POST">
                        <label class="form-check-label" for="currency_symbol">Currency</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <select class="form-control show-tick" id="currency" name="currency">
                                    <option value="USD"  <?php echo ($wo['config']['currency'] == 'USD')   ? ' selected' : '';?>>USD</option>
                                    <option value="EUR" <?php echo ($wo['config']['currency'] == 'EUR')   ? ' selected' : '';?>>EUR</option>
                                    <option value="JPY" <?php echo ($wo['config']['currency'] == 'JPY')   ? ' selected' : '';?>>JPY</option>
                                    <option value="TRY" <?php echo ($wo['config']['currency'] == 'TRY')   ? ' selected' : '';?>>TRY</option>
                                    <option value="GBP" <?php echo ($wo['config']['currency'] == 'GBP')   ? ' selected' : '';?>>GBP</option>
                                    <option value="RUB" <?php echo ($wo['config']['currency'] == 'RUB')   ? ' selected' : '';?>>RUB</option>
                                    <option value="PLN" <?php echo ($wo['config']['currency'] == 'PLN')   ? ' selected' : '';?>>PLN</option>
                                    <option value="ILS" <?php echo ($wo['config']['currency'] == 'ILS')   ? ' selected' : '';?>>ILS</option>
                                    <option value="BRL" <?php echo ($wo['config']['currency'] == 'BRL')   ? ' selected' : '';?>>BRL</option>
                                    <option value="INR" <?php echo ($wo['config']['currency'] == 'INR')   ? ' selected' : '';?>>INR</option>
                                </select>
                            </div>
                        </div>
                        <label class="form-check-label" for="currency_symbol">Currency symbol</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="currency_symbol" name="currency_symbol" class="form-control" value="<?php echo $wo['config']['currency_symbol'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">2Checkout payment</h6>
                    <div class="checkout-settings-alert"></div>
                    <form class="checkout-settings" method="POST">
                        <label for="checkout_payment">2Checkout Payment Method </label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="checkout_payment" id="checkout_payment-enabled" value="yes" <?php echo ($wo['config']['checkout_payment'] == 'yes') ? 'checked': '';?>>
                                <label class="form-check-label" for="checkout_payment-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="checkout_payment" id="checkout_payment-disabled" value="no" <?php echo ($wo['config']['checkout_payment'] == 'no') ? 'checked': '';?>>
                                <label class="form-check-label" for="checkout_payment-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="checkout_mode">2Checkout Mode</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="checkout_mode" id="checkout_mode-enabled" value="live" <?php echo ($wo['config']['checkout_mode'] == 'live') ? 'checked': '';?>>
                                <label class="form-check-label" for="checkout_mode-enabled">Live</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="checkout_mode" id="checkout_mode-disabled" value="sandbox" <?php echo ($wo['config']['checkout_mode'] == 'sandbox') ? 'checked': '';?>>
                                <label class="form-check-label" for="checkout_mode-disabled" class="m-l-20">SandBox</label>
                            </div>
                        </div> 
                        <br>
                        <label for="checkout_currency">2Checkout Currency</label>
                        <select class="form-control show-tick" id="checkout_currency" name="checkout_currency">
                            <option value="USD" <?php echo ($wo['config']['checkout_currency'] == 'USD')  ? ' selected': '';?>>USD</option>
                            <option value="EUR" <?php echo ($wo['config']['checkout_currency'] == 'EUR')  ? ' selected': '';?>>EUR</option>
                            <option value="AED" <?php echo ($wo['config']['checkout_currency'] == 'AED')  ? ' selected': '';?>>AED</option>
                            <option value="AFN" <?php echo ($wo['config']['checkout_currency'] == 'AFN')  ? ' selected': '';?>>AFN</option>
                            <option value="ALL" <?php echo ($wo['config']['checkout_currency'] == 'ALL')  ? ' selected': '';?>>ALL</option>
                            <option value="ARS" <?php echo ($wo['config']['checkout_currency'] == 'ARS')  ? ' selected': '';?>>ARS</option>
                            <option value="AUD" <?php echo ($wo['config']['checkout_currency'] == 'AUD')  ? ' selected': '';?>>AUD</option>
                            <option value="AZN" <?php echo ($wo['config']['checkout_currency'] == 'AZN')  ? ' selected': '';?>>AZN</option>
                            <option value="BBD" <?php echo ($wo['config']['checkout_currency'] == 'BBD')  ? ' selected': '';?>>BBD</option>
                            <option value="BDT" <?php echo ($wo['config']['checkout_currency'] == 'BDT')  ? ' selected': '';?>>BDT</option>
                            <option value="BGN" <?php echo ($wo['config']['checkout_currency'] == 'BGN')  ? ' selected': '';?>>BGN</option>
                            <option value="BMD" <?php echo ($wo['config']['checkout_currency'] == 'BMD')  ? ' selected': '';?>>BMD</option>
                            <option value="BND" <?php echo ($wo['config']['checkout_currency'] == 'BND')  ? ' selected': '';?>>BND</option>
                            <option value="BOB" <?php echo ($wo['config']['checkout_currency'] == 'BOB')  ? ' selected': '';?>>BOB</option>
                            <option value="BRL" <?php echo ($wo['config']['checkout_currency'] == 'BRL')  ? ' selected': '';?>>BRL</option>
                            <option value="BSD" <?php echo ($wo['config']['checkout_currency'] == 'BSD')  ? ' selected': '';?>>BSD</option>
                            <option value="BWP" <?php echo ($wo['config']['checkout_currency'] == 'BWP')  ? ' selected': '';?>>BWP</option>
                            <option value="BYN" <?php echo ($wo['config']['checkout_currency'] == 'BYN')  ? ' selected': '';?>>BYN</option>
                            <option value="BZD" <?php echo ($wo['config']['checkout_currency'] == 'BZD')  ? ' selected': '';?>>BZD</option>
                            <option value="CAD" <?php echo ($wo['config']['checkout_currency'] == 'CAD')  ? ' selected': '';?>>CAD</option>
                            <option value="CHF" <?php echo ($wo['config']['checkout_currency'] == 'CHF')  ? ' selected': '';?>>CHF</option>
                            <option value="CLP" <?php echo ($wo['config']['checkout_currency'] == 'CLP')  ? ' selected': '';?>>CLP</option>
                            <option value="CNY" <?php echo ($wo['config']['checkout_currency'] == 'CNY')  ? ' selected': '';?>>CNY</option>
                            <option value="COP" <?php echo ($wo['config']['checkout_currency'] == 'COP')  ? ' selected': '';?>>COP</option>
                            <option value="CRC" <?php echo ($wo['config']['checkout_currency'] == 'CRC')  ? ' selected': '';?>>CRC</option>
                            <option value="CZK" <?php echo ($wo['config']['checkout_currency'] == 'CZK')  ? ' selected': '';?>>CZK</option>
                            <option value="DKK" <?php echo ($wo['config']['checkout_currency'] == 'DKK')  ? ' selected': '';?>>DKK</option>
                            <option value="DOP" <?php echo ($wo['config']['checkout_currency'] == 'DOP')  ? ' selected': '';?>>DOP</option>
                            <option value="DZD" <?php echo ($wo['config']['checkout_currency'] == 'DZD')  ? ' selected': '';?>>DZD</option>
                            <option value="EGP" <?php echo ($wo['config']['checkout_currency'] == 'EGP')  ? ' selected': '';?>>EGP</option>
                            <option value="FJD" <?php echo ($wo['config']['checkout_currency'] == 'FJD')  ? ' selected': '';?>>FJD</option>
                            <option value="GBP" <?php echo ($wo['config']['checkout_currency'] == 'GBP')  ? ' selected': '';?>>GBP</option>
                            <option value="GTQ" <?php echo ($wo['config']['checkout_currency'] == 'GTQ')  ? ' selected': '';?>>GTQ</option>
                            <option value="HKD" <?php echo ($wo['config']['checkout_currency'] == 'HKD')  ? ' selected': '';?>>HKD</option>
                            <option value="HNL" <?php echo ($wo['config']['checkout_currency'] == 'HNL')  ? ' selected': '';?>>HNL</option>
                            <option value="HRK" <?php echo ($wo['config']['checkout_currency'] == 'HRK')  ? ' selected': '';?>>HRK</option>
                            <option value="HUF" <?php echo ($wo['config']['checkout_currency'] == 'HUF')  ? ' selected': '';?>>HUF</option>
                            <option value="IDR" <?php echo ($wo['config']['checkout_currency'] == 'IDR')  ? ' selected': '';?>>IDR</option>
                            <option value="ILS" <?php echo ($wo['config']['checkout_currency'] == 'ILS')  ? ' selected': '';?>>ILS</option>
                            <option value="INR" <?php echo ($wo['config']['checkout_currency'] == 'INR')  ? ' selected': '';?>>INR</option>
                            <option value="JMD" <?php echo ($wo['config']['checkout_currency'] == 'JMD')  ? ' selected': '';?>>JMD</option>
                            <option value="JOD" <?php echo ($wo['config']['checkout_currency'] == 'JOD')  ? ' selected': '';?>>JOD</option>
                            <option value="JPY" <?php echo ($wo['config']['checkout_currency'] == 'JPY')  ? ' selected': '';?>>JPY</option>
                            <option value="KES" <?php echo ($wo['config']['checkout_currency'] == 'KES')  ? ' selected': '';?>>KES</option>
                            <option value="KRW" <?php echo ($wo['config']['checkout_currency'] == 'KRW')  ? ' selected': '';?>>KRW</option>
                            <option value="KWD" <?php echo ($wo['config']['checkout_currency'] == 'KWD')  ? ' selected': '';?>>KWD</option>
                            <option value="KZT" <?php echo ($wo['config']['checkout_currency'] == 'KZT')  ? ' selected': '';?>>KZT</option>
                            <option value="LAK" <?php echo ($wo['config']['checkout_currency'] == 'LAK')  ? ' selected': '';?>>LAK</option>
                            <option value="LBP" <?php echo ($wo['config']['checkout_currency'] == 'LBP')  ? ' selected': '';?>>LBP</option>
                            <option value="LKR" <?php echo ($wo['config']['checkout_currency'] == 'LKR')  ? ' selected': '';?>>LKR</option>
                            <option value="LRD" <?php echo ($wo['config']['checkout_currency'] == 'LRD')  ? ' selected': '';?>>LRD</option>
                            <option value="MAD" <?php echo ($wo['config']['checkout_currency'] == 'MAD')  ? ' selected': '';?>>MAD</option>
                            <option value="MDL" <?php echo ($wo['config']['checkout_currency'] == 'MDL')  ? ' selected': '';?>>MDL</option>
                            <option value="MMK" <?php echo ($wo['config']['checkout_currency'] == 'MMK')  ? ' selected': '';?>>MMK</option>
                            <option value="MOP" <?php echo ($wo['config']['checkout_currency'] == 'MOP')  ? ' selected': '';?>>MOP</option>
                            <option value="MRO" <?php echo ($wo['config']['checkout_currency'] == 'MRO')  ? ' selected': '';?>>MRO</option>
                            <option value="MUR" <?php echo ($wo['config']['checkout_currency'] == 'MUR')  ? ' selected': '';?>>MUR</option>
                            <option value="MVR" <?php echo ($wo['config']['checkout_currency'] == 'MVR')  ? ' selected': '';?>>MVR</option>
                            <option value="MXN" <?php echo ($wo['config']['checkout_currency'] == 'MXN')  ? ' selected': '';?>>MXN</option>
                            <option value="MYR" <?php echo ($wo['config']['checkout_currency'] == 'MYR')  ? ' selected': '';?>>MYR</option>
                            <option value="NAD" <?php echo ($wo['config']['checkout_currency'] == 'NAD')  ? ' selected': '';?>>NAD</option>
                            <option value="NGN" <?php echo ($wo['config']['checkout_currency'] == 'NGN')  ? ' selected': '';?>>NGN</option>
                            <option value="NIO" <?php echo ($wo['config']['checkout_currency'] == 'NIO')  ? ' selected': '';?>>NIO</option>
                            <option value="NOK" <?php echo ($wo['config']['checkout_currency'] == 'NOK')  ? ' selected': '';?>>NOK</option>
                            <option value="NPR" <?php echo ($wo['config']['checkout_currency'] == 'NPR')  ? ' selected': '';?>>NPR</option>
                            <option value="NZD" <?php echo ($wo['config']['checkout_currency'] == 'NZD')  ? ' selected': '';?>>NZD</option>
                            <option value="OMR" <?php echo ($wo['config']['checkout_currency'] == 'OMR')  ? ' selected': '';?>>OMR</option>
                            <option value="PEN" <?php echo ($wo['config']['checkout_currency'] == 'PEN')  ? ' selected': '';?>>PEN</option>
                            <option value="PGK" <?php echo ($wo['config']['checkout_currency'] == 'PGK')  ? ' selected': '';?>>PGK</option>
                            <option value="PHP" <?php echo ($wo['config']['checkout_currency'] == 'PHP')  ? ' selected': '';?>>PHP</option>
                            <option value="PKR" <?php echo ($wo['config']['checkout_currency'] == 'PKR')  ? ' selected': '';?>>PKR</option>
                            <option value="PLN" <?php echo ($wo['config']['checkout_currency'] == 'PLN')  ? ' selected': '';?>>PLN</option>
                            <option value="PYG" <?php echo ($wo['config']['checkout_currency'] == 'PYG')  ? ' selected': '';?>>PYG</option>
                            <option value="QAR" <?php echo ($wo['config']['checkout_currency'] == 'QAR')  ? ' selected': '';?>>QAR</option>
                            <option value="RON" <?php echo ($wo['config']['checkout_currency'] == 'RON')  ? ' selected': '';?>>RON</option>
                            <option value="RSD" <?php echo ($wo['config']['checkout_currency'] == 'RSD')  ? ' selected': '';?>>RSD</option>
                            <option value="RUB" <?php echo ($wo['config']['checkout_currency'] == 'RUB')  ? ' selected': '';?>>RUB</option>
                            <option value="SAR" <?php echo ($wo['config']['checkout_currency'] == 'SAR')  ? ' selected': '';?>>SAR</option>
                            <option value="SBD" <?php echo ($wo['config']['checkout_currency'] == 'SBD')  ? ' selected': '';?>>SBD</option>
                            <option value="SCR" <?php echo ($wo['config']['checkout_currency'] == 'SCR')  ? ' selected': '';?>>SCR</option>
                            <option value="SEK" <?php echo ($wo['config']['checkout_currency'] == 'SEK')  ? ' selected': '';?>>SEK</option>
                            <option value="SGD" <?php echo ($wo['config']['checkout_currency'] == 'SGD')  ? ' selected': '';?>>SGD</option>
                            <option value="SYP" <?php echo ($wo['config']['checkout_currency'] == 'SYP')  ? ' selected': '';?>>SYP</option>
                            <option value="THB" <?php echo ($wo['config']['checkout_currency'] == 'THB')  ? ' selected': '';?>>THB</option>
                            <option value="TND" <?php echo ($wo['config']['checkout_currency'] == 'TND')  ? ' selected': '';?>>TND</option>
                            <option value="TOP" <?php echo ($wo['config']['checkout_currency'] == 'TOP')  ? ' selected': '';?>>TOP</option>
                            <option value="TRY" <?php echo ($wo['config']['checkout_currency'] == 'TRY')  ? ' selected': '';?>>TRY</option>
                            <option value="TTD" <?php echo ($wo['config']['checkout_currency'] == 'TTD')  ? ' selected': '';?>>TTD</option>
                            <option value="TWD" <?php echo ($wo['config']['checkout_currency'] == 'TWD')  ? ' selected': '';?>>TWD</option>
                            <option value="UAH" <?php echo ($wo['config']['checkout_currency'] == 'UAH')  ? ' selected': '';?>>UAH</option>
                            <option value="UYU" <?php echo ($wo['config']['checkout_currency'] == 'UYU')  ? ' selected': '';?>>UYU</option>
                            <option value="VND" <?php echo ($wo['config']['checkout_currency'] == 'VND')  ? ' selected': '';?>>VND</option>
                            <option value="VUV" <?php echo ($wo['config']['checkout_currency'] == 'VUV')  ? ' selected': '';?>>VUV</option>
                            <option value="WST" <?php echo ($wo['config']['checkout_currency'] == 'WST')  ? ' selected': '';?>>WST</option>
                            <option value="XCD" <?php echo ($wo['config']['checkout_currency'] == 'XCD')  ? ' selected': '';?>>XCD</option>
                            <option value="XOF" <?php echo ($wo['config']['checkout_currency'] == 'XOF')  ? ' selected': '';?>>XOF</option>
                            <option value="YER" <?php echo ($wo['config']['checkout_currency'] == 'YER')  ? ' selected': '';?>>YER</option>
                            <option value="ZAR" <?php echo ($wo['config']['checkout_currency'] == 'ZAR')  ? ' selected': '';?>>ZAR</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Seller ID</label>
                                <input type="text" id="checkout_seller_id" name="checkout_seller_id" class="form-control" value="<?php echo $wo['config']['checkout_seller_id'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Publishable Key</label>
                                <input type="text" id="checkout_publishable_key" name="checkout_publishable_key" class="form-control" value="<?php echo $wo['config']['checkout_publishable_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Private Key</label>
                                <input type="text" id="checkout_private_key" name="checkout_private_key" class="form-control" value="<?php echo $wo['config']['checkout_private_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cashfree payment</h6>
                    <div class="cashfree-settings-alert"></div>
                    <form class="cashfree-settings" method="POST">
                        <label for="cashfree_payment">Cashfree Payment Method </label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="cashfree_payment" id="cashfree_payment-enabled" value="yes" <?php echo ($wo['config']['cashfree_payment'] == 'yes') ? 'checked': '';?>>
                                <label class="form-check-label" for="cashfree_payment-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="cashfree_payment" id="cashfree_payment-disabled" value="no" <?php echo ($wo['config']['cashfree_payment'] == 'no') ? 'checked': '';?>>
                                <label class="form-check-label" for="cashfree_payment-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="cashfree_mode">Cashfree Mode</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="cashfree_mode" id="cashfree_mode-enabled" value="sandBox" <?php echo ($wo['config']['cashfree_mode'] == 'sandBox') ? 'checked': '';?>>
                                <label class="form-check-label" for="cashfree_mode-enabled">SandBox</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="cashfree_mode" id="cashfree_mode-disabled" value="live" <?php echo ($wo['config']['cashfree_mode'] == 'live') ? 'checked': '';?>>
                                <label class="form-check-label" for="cashfree_mode-disabled" class="m-l-20">Live</label>
                            </div>
                        </div> 
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Client Id</label>
                                <input type="text" id="cashfree_client_key" name="cashfree_client_key" class="form-control" value="<?php echo $wo['config']['cashfree_client_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Client Secret</label>
                                <input type="text" id="cashfree_secret_key" name="cashfree_secret_key" class="form-control" value="<?php echo $wo['config']['cashfree_secret_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Local bank payment</h6>
                    <div class="bank-settings-alert"></div>
                    <form class="bank-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Bank Description</label>
                                <textarea name="bank_description" id="bank_description" class="form-control" cols="30" rows="5"><?php echo $wo['config']['bank_description']; ?></textarea>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Bank transfer note</label>
                                <textarea name="bank_transfer_note" id="bank_transfer_note" class="form-control" cols="30" rows="5"><?php echo $wo['config']['bank_transfer_note']; ?></textarea>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Paysera SMS payment</h6>
                    <div class="pay-settings-alert"></div>
                    <form class="pay-settings" method="POST">
                        <label for="currency_symbol">Project ID</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="paysera_project_id" name="paysera_project_id" class="form-control" value="<?php echo $wo['config']['paysera_project_id'];?>">
                            </div>
                        </div>
                        <label class="form-check-label" for="currency_symbol">Project password</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="paysera_password" name="paysera_password" class="form-control" value="<?php echo $wo['config']['paysera_password'];?>">
                            </div>
                        </div>
                        <label for="paysera_test_mode">Test mode</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="paysera_test_mode" id="paysera_test_mode-enabled" value="live" <?php echo ($wo['config']['paysera_test_mode'] == 'live') ? 'checked': '';?>>
                                <label class="form-check-label" for="paysera_test_mode-enabled">Live</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="paysera_test_mode" id="paysera_test_mode-disabled" value="test" <?php echo ($wo['config']['paysera_test_mode'] == 'test') ? 'checked': '';?>>
                                <label class="form-check-label" for="paysera_test_mode-disabled" class="m-l-20">Test</label>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <!--Paypal payment-->
        <div class="col-lg-6 col-md-6 float-right">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Paypal payment</h6>
                    <div class="paypal-settings-alert"></div>
                    <form class="paypal-settings" method="POST">
                        <label for="paypal_mode">PayPal Mode</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="paypal_mode" id="paypal_mode-enabled" value="live" <?php echo ($wo['config']['paypal_mode'] == 'live') ? 'checked': '';?>>
                                <label class="form-check-label" for="paypal_mode-enabled">Live</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="paypal_mode" id="paypal_mode-disabled" value="sandbox" <?php echo ($wo['config']['paypal_mode'] == 'sandbox') ? 'checked': '';?>>
                                <label class="form-check-label" for="paypal_mode-disabled" class="m-l-20">SandBox</label>
                            </div>
                        </div> 
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">PayPal Client ID</label>
                                <input type="text" id="paypal_id" name="paypal_id" class="form-control" value="<?php echo $wo['config']['paypal_id'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">PayPal Secret Key</label>
                                <input type="text" id="paypal_secret" name="paypal_secret" class="form-control" value="<?php echo $wo['config']['paypal_secret'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Stripe payment</h6>
                    <div class="stripe-settings-alert"></div>
                    <form class="stripe-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Stripe version</label>
                                <input type="text" id="stripe_version" name="stripe_version" class="form-control" value="<?php echo $wo['config']['stripe_version'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Stripe API Secret Key <small>Your Stripe secret key that starts with sk_</small></label>
                                <input type="text" id="stripe_secret" name="stripe_secret" class="form-control" value="<?php echo $wo['config']['stripe_secret'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Stripe Publishable Key <small>Your Stripe publishable key that starts with pk_</small></label>
                                <input type="text" id="stripe_id" name="stripe_id" class="form-control" value="<?php echo $wo['config']['stripe_id'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Iyzipay payment</h6>
                    <div class="iyzipay-settings-alert"></div>
                    <form class="iyzipay-settings" method="POST">
                        <label for="iyzipay_payment">Iyzipay Payment Method </label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="iyzipay_payment" id="iyzipay_payment-enabled" value="yes" <?php echo ($wo['config']['iyzipay_payment'] == 'yes') ? 'checked': '';?>>
                                <label class="form-check-label" for="iyzipay_payment-enabled">Enabled</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="iyzipay_payment" id="iyzipay_payment-disabled" value="no" <?php echo ($wo['config']['iyzipay_payment'] == 'no') ? 'checked': '';?>>
                                <label class="form-check-label" for="iyzipay_payment-disabled" class="m-l-20">Disabled</label>
                            </div>
                        </div>
                        <label for="iyzipay_mode">Iyzipay Mode</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="iyzipay_mode" id="iyzipay_mode-enabled" value="0" <?php echo ($wo['config']['iyzipay_mode'] == '0') ? 'checked': '';?>>
                                <label class="form-check-label" for="iyzipay_mode-enabled">Live</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="iyzipay_mode" id="iyzipay_mode-disabled" value="1" <?php echo ($wo['config']['iyzipay_mode'] == '1') ? 'checked': '';?>>
                                <label class="form-check-label" for="iyzipay_mode-disabled" class="m-l-20">SandBox</label>
                            </div>
                        </div> 
                        <div class="clearfix"></div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Key</label>
                                <input type="text" id="iyzipay_key" name="iyzipay_key" class="form-control" value="<?php echo $wo['config']['iyzipay_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Secret Key</label>
                                <input type="text" id="iyzipay_secret_key" name="iyzipay_secret_key" class="form-control" value="<?php echo $wo['config']['iyzipay_secret_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Id</label>
                                <input type="text" id="iyzipay_buyer_id" name="iyzipay_buyer_id" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_id'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Name</label>
                                <input type="text" id="iyzipay_buyer_name" name="iyzipay_buyer_name" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_name'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Surname</label>
                                <input type="text" id="iyzipay_buyer_surname" name="iyzipay_buyer_surname" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_surname'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Gsm Number (+905350000000)</label>
                                <input type="text" id="iyzipay_buyer_gsm_number" name="iyzipay_buyer_gsm_number" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_gsm_number'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Email</label>
                                <input type="text" id="iyzipay_buyer_email" name="iyzipay_buyer_email" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_email'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Identity Number</label>
                                <input type="text" id="iyzipay_identity_number" name="iyzipay_identity_number" class="form-control" value="<?php echo $wo['config']['iyzipay_identity_number'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Address</label>
                                <input type="text" id="iyzipay_address" name="iyzipay_address" class="form-control" value="<?php echo $wo['config']['iyzipay_address'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer City</label>
                                <input type="text" id="iyzipay_city" name="iyzipay_city" class="form-control" value="<?php echo $wo['config']['iyzipay_city'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Country</label>
                                <input type="text" id="iyzipay_country" name="iyzipay_country" class="form-control" value="<?php echo $wo['config']['iyzipay_country'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Zip</label>
                                <input type="text" id="iyzipay_zip" name="iyzipay_zip" class="form-control" value="<?php echo $wo['config']['iyzipay_zip'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    var form_payment_settings = $('form.payment-settings');
    form_payment_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_payment_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_payment_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.payment-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.payment-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_paypal_settings = $('form.paypal-settings');
    form_paypal_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_paypal_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_paypal_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.paypal-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.paypal-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_stripe_settings = $('form.stripe-settings');
    form_stripe_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_stripe_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_stripe_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.stripe-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.stripe-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_checkout_settings = $('form.checkout-settings');
    form_checkout_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_checkout_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_checkout_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.checkout-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.checkout-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_cashfree_settings = $('form.cashfree-settings');
    form_cashfree_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_cashfree_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_cashfree_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.cashfree-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.cashfree-settings-alert').empty();
                }, 2000);
            }
        }
    });
    
    var form_iyzipay_settings = $('form.iyzipay-settings');
    form_iyzipay_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_iyzipay_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_iyzipay_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.iyzipay-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.iyzipay-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_bankpayment_settings = $('form.bank-settings');
    form_bankpayment_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_bankpayment_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_bankpayment_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.bank-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.bank-settings-alert').empty();
                }, 2000);
            }
        }
    });

    var form_pay_settings = $('form.pay-settings');
    form_pay_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting&p=payment-settings',
        beforeSend: function() {
            form_pay_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_pay_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.pay-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Settings updated successfully</div>');
                setTimeout(function () {
                    $('.pay-settings-alert').empty();
                }, 2000);
            }
        }
    });
});
</script>